### Create a new Post
POST http://localhost:5000/api/v1/posts
content-type: application/json

{
     "title": "My first post",
     "body": "This is my first post  and I will be posting it to the website at http://localhost and I will be posting it to the website at http://localhost and I will be posting it to the website at http://localhost and I will",    
}

### get all posts
GET http://localhost:5000/api/v1/posts

### get a single post by ID
GET http://localhost:5000/api/v1/posts/id/11212